import { api } from "./client";

export const coursesApi = {
  getAll: (queryString) => api.get(`/courses?${queryString}`),
  getById: (id) => api.get(`/courses/${id}`),
  getLearningData: (id) => api.get(`/courses/${id}/curriculum`),
  getObjectives: (id) => api.get(`/courses/${id}/objectives`),
  getFirstLesson: (id) => api.get(`/courses/${id}/first-lesson`),
  getReviews: (queryString, courseId) => api.get(`/courses/${courseId}/reviews?${queryString}`),
  getReviewDetails: (courseId) => api.get(`/courses/${courseId}/reviews/summary`),
  createReview: ({ courseId, description, rating }) => api.post(`/courses/${courseId}/reviews`, { description, rating }),
  getReview: (courseId) => api.get(`/courses/${courseId}/reviews/me`),
  enrollCourse: (courseId) => api.post(`/courses/${courseId}/enrollments`),
  getEnrollment: (courseId) => api.get(`/courses/${courseId}/enrollments`),
  createCourseProgress: (courseId) => api.post(`/courses/${courseId}/progress`),
  getCourseProgress: (courseId) => api.get(`/courses/${courseId}/progress`),
  updateCourseProgress: (courseId, data) => api.patch(`/courses/${courseId}/progress`, data),
  getRecentlyViewed: () => api.get("/users/me/courses/recently-viewed"),
  getRecommended: () => api.get("/users/me/courses/recommended"),
  getPopular: () => api.get("/courses/popular"),
  getInProgress: () => api.get("/users/me/courses/in-progress"),
  getCompleted: () => api.get("/users/me/courses/completed"),
  claimCertificate: (courseId) => api.post(`/courses/${courseId}/certificates`),
  getCertificate: (courseId) => api.get(`/courses/${courseId}/certificates`),
  checkCertificateEligibility: (courseId) => api.get(`/courses/${courseId}/certificates/check`),
  getCourseLessonCompletions: (courseId) => api.get(`/courses/${courseId}/completions`),
  getMyCertificates: () => api.get("/users/me/certificates"),
  getCertificateById: (id) => api.get(`/certificates/${id}`),
};
