export const queryKeys = {
  me: () => ["me"],
  profile: () => ["profile"],
  xpEarned: () => ["xp-earned"],
  xpTransactions: (params) => ["xp-transactions", params],
  xpTransactionsRoot: () => ["xp-transactions"],
  activities: (params) => ["activities", params],
  activitiesInfinite: () => ["activities", "infinite"],
  activitiesRoot: () => ["activities"],

  categories: () => ["categories"],
  courses: (params) => ["courses", params],
  courseDetails: (courseId) => ["course-details", courseId],
  courseObjectives: (courseId) => ["course-objectives", courseId],
  popularCourses: () => ["popular-course"],

  courseLearningData: (courseId) => ["course-learning-data", courseId],
  firstLesson: (courseId) => ["first-lesson", courseId],
  enrollment: (courseId) => ["enrolled", courseId],
  courseProgress: (courseId) => ["course-progress", courseId],
  courseLessonCompletions: (courseId) => [
    "course-lesson-completions",
    courseId,
  ],
  courseLessonCompletionsRoot: () => ["course-lesson-completions"],
  certificate: (courseId) => ["certificate", courseId],
  certificateEligibility: (courseId) => ["certificate-eligibility", courseId],
  myCertificates: () => ["my-certificates"],
  myCertificatesPage: (params) => ["my-certificates", params],
  certificateById: (id) => ["certificate-by-id", id],

  lessonContent: (lessonId) => ["lesson-content", lessonId],
  quizzes: (lessonId) => ["quizzes", lessonId],
  completedLesson: (lessonId) => ["get-completed-lesson", lessonId],
  quizAttempts: (lessonId) => ["quiz-attempts", lessonId],
  quizAttemptLatest: (lessonId) => ["quiz-attempt-latest", lessonId],

  reviews: (courseId, params) => ["reviews", courseId, params],
  reviewsRoot: (courseId) => ["reviews", courseId],
  reviewsInfinite: (courseId, filters) => [
    "reviews-infinite",
    courseId,
    filters,
  ],
  reviewsInfiniteRoot: (courseId) => ["reviews-infinite", courseId],
  reviewDetails: (courseId) => ["review-details", courseId],
  myReview: (courseId) => ["review-me", courseId],

  activeSubscription: () => ["active-subscription"],
  subscription: (planId) => ["subscription", planId],
  plans: () => ["plans"],
  paymentsRoot: () => ["payments"],
  payments: (params) => ["payments", params],
  payment: (id) => ["payment", id],

  recentlyViewed: () => ["get-recently-viewed-courses"],
  recommended: () => ["recommended-course"],
  inProgress: () => ["course-in-progress"],
  completed: () => ["completed-course"],

  savedCourses: (params) => ["saved-courses", params],
  savedCoursesRoot: () => ["saved-courses"],
  savedCourseIds: () => ["saved-course-ids"],
};

export const userScopedQueryRoots = new Set([
  queryKeys.me()[0],
  queryKeys.profile()[0],
  queryKeys.xpEarned()[0],
  queryKeys.xpTransactionsRoot()[0],
  queryKeys.activitiesRoot()[0],
  queryKeys.enrollment(null)[0],
  queryKeys.courseProgress(null)[0],
  queryKeys.courseLessonCompletions(null)[0],
  queryKeys.completedLesson(null)[0],
  queryKeys.quizAttempts(null)[0],
  queryKeys.quizAttemptLatest(null)[0],
  queryKeys.certificate(null)[0],
  queryKeys.certificateEligibility(null)[0],
  queryKeys.myCertificates()[0],
  queryKeys.certificateById(null)[0],
  queryKeys.myReview(null)[0],
  queryKeys.activeSubscription()[0],
  queryKeys.subscription(null)[0],
  queryKeys.paymentsRoot()[0],
  queryKeys.payment(null)[0],
  queryKeys.recentlyViewed()[0],
  queryKeys.recommended()[0],
  queryKeys.inProgress()[0],
  queryKeys.completed()[0],
  queryKeys.savedCoursesRoot()[0],
  queryKeys.savedCourseIds()[0],
]);
